-- ZOVRO TECH SUPABASE SETUP
-- Run this in Supabase SQL Editor.
-- Public website can INSERT leads. Do NOT add a public SELECT policy in production.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  plan text default 'General Enquiry',
  message text not null,
  status text not null default 'New',
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

drop policy if exists "public_insert_leads" on public.leads;
create policy "public_insert_leads"
on public.leads for insert
to anon
with check (true);

-- IMPORTANT:
-- The admin page should NOT be given public SELECT/UPDATE access.
-- For a secure production dashboard, enable Supabase Auth and create
-- authenticated-user policies for SELECT/UPDATE.
--
-- Example after creating an admin Auth user:
--
-- create policy "admin_read_leads"
-- on public.leads for select to authenticated
-- using (auth.uid() = 'YOUR_ADMIN_USER_UUID');
--
-- create policy "admin_update_leads"
-- on public.leads for update to authenticated
-- using (auth.uid() = 'YOUR_ADMIN_USER_UUID')
-- with check (auth.uid() = 'YOUR_ADMIN_USER_UUID');
