-- ZOVRO TECH lead system
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  plan text not null,
  message text not null,
  status text not null default 'New' check (status in ('New','Contacted','Converted','Lost')),
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;
alter table public.admins enable row level security;

-- Public website: submit only. No public read/update/delete.
drop policy if exists "public can submit leads" on public.leads;
create policy "public can submit leads"
on public.leads for insert to anon, authenticated
with check (true);

-- Admin access to leads.
drop policy if exists "admins can read leads" on public.leads;
create policy "admins can read leads"
on public.leads for select to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins can update leads" on public.leads;
create policy "admins can update leads"
on public.leads for update to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins can delete leads" on public.leads;
create policy "admins can delete leads"
on public.leads for delete to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- Admin can only see their own admin row. Do NOT create an insert policy here.
drop policy if exists "admins can read own row" on public.admins;
create policy "admins can read own row"
on public.admins for select to authenticated
using (user_id = auth.uid());

-- Data API grants.
grant insert on public.leads to anon, authenticated;
grant select, update, delete on public.leads to authenticated;
grant select on public.admins to authenticated;

grant usage, select on sequence public.leads_id_seq to anon, authenticated;

-- Optional: enable Realtime for the live dashboard.
alter publication supabase_realtime add table public.leads;

-- AFTER creating your admin user in Supabase Auth, run this one line:
-- insert into public.admins (user_id) values ('PASTE_AUTH_USER_UUID_HERE');
