-- ZOVRO TECH
-- Run this in Supabase SQL Editor if your existing tables do not already match.
-- This creates the exact tables expected by index.html and admin.html.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text not null,
  service text not null,
  details text not null
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text not null,
  service text not null,
  date date not null,
  time text not null,
  message text default ''
);

alter table public.leads enable row level security;
alter table public.appointments enable row level security;

-- Public website may INSERT enquiries/bookings.
drop policy if exists "public insert leads" on public.leads;
create policy "public insert leads" on public.leads
for insert to anon, authenticated
with check (true);

drop policy if exists "public insert appointments" on public.appointments;
create policy "public insert appointments" on public.appointments
for insert to anon, authenticated
with check (true);

-- IMPORTANT:
-- The admin.html shown here uses the same anon key, so SELECT policies make
-- the data readable to anyone who knows the public API. For a truly secure
-- production admin, use Supabase Auth and restrict SELECT to an admin role.
-- These policies are included only for the simple ready-to-use dashboard.
drop policy if exists "dashboard read leads" on public.leads;
create policy "dashboard read leads" on public.leads
for select to anon, authenticated
using (true);

drop policy if exists "dashboard read appointments" on public.appointments;
create policy "dashboard read appointments" on public.appointments
for select to anon, authenticated
using (true);
