const db=window.supabaseClient;const $=s=>document.querySelector(s);let creds=null;
function setStatus(el,msg,type=""){el.className="form-status "+type;el.textContent=msg}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const u=$("#username").value.trim(),p=$("#password").value;setStatus($("#loginStatus"),"Checking...");try{const {data,error}=await db.rpc("admin_login",{p_username:u,p_password:p});if(error)throw error;if(!data?.ok)throw new Error("Invalid credentials");creds={u,p};sessionStorage.setItem("zovroAdmin",JSON.stringify(creds));showDash();await load()}catch(err){console.error(err);setStatus($("#loginStatus"),"Invalid username or password.","error")}});
function showDash(){$("#loginView").classList.add("hidden");$("#dashView").classList.remove("hidden")}
function logout(){sessionStorage.removeItem("zovroAdmin");creds=null;location.reload()}$("#logout").onclick=logout;
async function load(){if(!creds)return;try{const {data,error}=await db.rpc("admin_get_dashboard",{p_username:creds.u,p_password:creds.p});if(error)throw error;if(!data?.ok)throw new Error("Session invalid");render(data);$("#lastSync").textContent=new Date().toLocaleTimeString()}catch(e){console.error(e);setStatus($("#loginStatus"),"Dashboard connection failed. Run schema.sql in Supabase first.","error");logout()}}
function render(d){const leads=d.leads||[],apps=d.appointments||[],m=d.metrics||{};$("#mLeads").textContent=m.total_leads||0;$("#mApps").textContent=m.appointments||0;$("#mNew").textContent=m.new_leads||0;$("#mConverted").textContent=m.converted||0;$("#statusTotal").textContent=(m.total_leads||0)+" total";$("#donutText").textContent=m.total_leads||0;$("#legendNew").textContent=m.new_leads||0;$("#legendContacted").textContent=m.contacted||0;$("#legendConverted").textContent=m.converted||0;const max=Math.max(...(d.activity||[1]),1);$("#bars").innerHTML=(d.activity||[]).map(v=>`<div class="bar" style="height:${Math.max(8,v/max*100)}%"></div>`).join("");$("#leadsBody").innerHTML=leads.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td>${esc(x.service)}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td>${fmt(x.created_at)}</td></tr>`).join("")||emptyRow(6,"No leads yet");$("#appsBody").innerHTML=apps.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td>${esc(x.service)}</td><td>${esc(x.preferred_date)}</td><td>${esc(x.preferred_time)}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td></tr>`).join("")||emptyRow(7,"No appointments yet")}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function fmt(v){return v?new Date(v).toLocaleDateString():"—"}function emptyRow(n,t){return `<tr><td colspan="${n}">${t}</td></tr>`}
document.querySelectorAll(".side-links button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".side-links button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tab").forEach(t=>t.classList.add("hidden"));$("#tab-"+b.dataset.tab).classList.remove("hidden")});
$("#refresh").onclick=load;$("#refresh2").onclick=load;
try{creds=JSON.parse(sessionStorage.getItem("zovroAdmin")||"null")}catch{}if(creds){showDash();load()}setInterval(()=>{if(creds&&!document.hidden)load()},15000);
