const {createClient}=window.supabase;const supabase=createClient(window.ZOVRO_CONFIG.supabaseUrl,window.ZOVRO_CONFIG.supabaseKey);let leads=[];const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const loginView=$('#loginView'),app=$('#app'),loginMsg=$('#loginMsg');
async function boot(){const {data:{session}}=await supabase.auth.getSession();if(session)await enter(session.user);}
async function enter(user){const {data:admin,error}=await supabase.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();if(error||!admin){loginMsg.textContent='This account is not an authorized admin.';await supabase.auth.signOut();return}loginView.classList.add('hidden');app.classList.remove('hidden');await loadLeads();subscribe();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();loginMsg.textContent='Signing in...';const {data,error}=await supabase.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error){loginMsg.textContent=error.message;return}await enter(data.user)});
$('#logout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});
async function loadLeads(){const {data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false});if(error){console.error(error);return}leads=data||[];render()}
function render(){const q=($('#search')?.value||'').toLowerCase();const st=$('#statusFilter')?.value||'all';const filtered=leads.filter(x=>(st==='all'||x.status===st)&&[x.name,x.email,x.phone,x.plan].join(' ').toLowerCase().includes(q));$('#total').textContent=leads.length;$('#newCount').textContent=leads.filter(x=>x.status==='New').length;$('#contacted').textContent=leads.filter(x=>x.status==='Contacted').length;$('#converted').textContent=leads.filter(x=>x.status==='Converted').length;$('#leadRows').innerHTML=filtered.length?filtered.map(row).join(''):'<tr><td colspan="7"><div class="empty">No leads found.</div></td></tr>';$('#latest').innerHTML=leads.slice(0,5).map(x=>`<div style="padding:15px 20px;border-bottom:1px solid #ffffff08;display:flex;justify-content:space-between;gap:12px"><div><b class="lead-name">${esc(x.name)}</b><div class="muted">${esc(x.plan)} · ${esc(x.email)}</div></div><button class="row-actions" onclick="openDetail('${x.id}')">View</button></div>`).join('')||'<div class="empty">No leads yet.</div>'}
function row(x){return `<tr><td><b class="lead-name">${esc(x.name)}</b><div class="muted">#${x.id}</div></td><td>${esc(x.email)}<div class="muted">${esc(x.phone||'')}</div></td><td>${esc(x.plan||'')}</td><td>${esc((x.message||'').slice(0,70))}${(x.message||'').length>70?'…':''}</td><td><select class="status-select" data-id="${x.id}"><option ${x.status==='New'?'selected':''}>New</option><option ${x.status==='Contacted'?'selected':''}>Contacted</option><option ${x.status==='Converted'?'selected':''}>Converted</option><option ${x.status==='Lost'?'selected':''}>Lost</option></select></td><td>${new Date(x.created_at).toLocaleString()}</td><td><div class="row-actions"><button onclick="openDetail('${x.id}')">View</button><button onclick="deleteLead('${x.id}')">Delete</button></div></td></tr>`}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#leadRows').addEventListener('change',async e=>{if(!e.target.matches('.status-select'))return;const id=e.target.dataset.id;const {error}=await supabase.from('leads').update({status:e.target.value}).eq('id',id);if(error)alert(error.message);else{const x=leads.find(a=>String(a.id)===String(id));if(x)x.status=e.target.value;render()}});
window.deleteLead=async id=>{if(!confirm('Delete this lead?'))return;const {error}=await supabase.from('leads').delete().eq('id',id);if(error)alert(error.message);else{leads=leads.filter(x=>String(x.id)!==String(id));render()}};
window.openDetail=id=>{const x=leads.find(a=>String(a.id)===String(id));if(!x)return;$('#detailName').textContent=x.name;$('#detailBody').innerHTML=`<div class="detail-grid"><div><small>Email</small><b>${esc(x.email)}</b></div><div><small>Phone</small><b>${esc(x.phone)}</b></div><div><small>Plan</small><b>${esc(x.plan)}</b></div><div><small>Status</small><b>${esc(x.status)}</b></div><div><small>Submitted</small><b>${new Date(x.created_at).toLocaleString()}</b></div></div><div class="detail-message">${esc(x.message)}</div>`;$('#detailModal').classList.remove('hidden')};
$('#closeModal').onclick=()=>$('#detailModal').classList.add('hidden');$('#refresh').onclick=loadLeads;$('#search').oninput=render;$('#statusFilter').onchange=render;$('#openLeads').onclick=()=>{$$('.view').forEach(v=>v.classList.add('hidden'));$('#leads').classList.remove('hidden');$$('[data-view]').forEach(b=>b.classList.remove('active'));document.querySelector('[data-view="leads"]').classList.add('active')};$$('[data-view]').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.view).classList.remove('hidden');$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function subscribe(){supabase.channel('leads-live').on('postgres_changes',{event:'*',schema:'public',table:'leads'},()=>loadLeads()).subscribe()}
boot();
